### ISSUE TITLE
Supporting k/v v2

### ISSUE THREAD

**Issue by petems** [petems/petems-hiera_vault#23]
It would be nice to be able to support the new k/v v2 backend, especially as it's now default for the main `kv` mount. 

## Blockers

Right now, the Vault gem does not have an easy way of using the new KV v2 backend

The following issues will need to be solved/merged before hiera_vault can support v2:

https://github.com/hashicorp/vault-ruby/issues/195
https://github.com/hashicorp/vault-ruby/pull/194
https://github.com/hashicorp/vault-ruby/pull/196

**Comment by maxadamo** [comment]
@petems a quick question: as far as you know, is it possible to upgrade the keystore on Vault from v1 to v2 :question:  Or do we need to copy the keys one by one :face_with_head_bandage:

**Comment by isbear** [comment]
Upgrade is possible, we did that. Read the documentation for v2 store, there's instructions for upgrading: https://www.vaultproject.io/docs/secrets/kv/kv-v2.html

**Note:** you have to modify your policies and clients to work with new paths.

**Comment by maxadamo** [comment]
for your reference. 
I created this tool: [maxadamo/vault-secrets-shuffle](https://github.com/hashicorp/maxadamo/vault-secrets-shuffle)
I had to use Go (the only language which fully supports V2 at the moment). 
The tool retrieves the hostnames from a Puppet DB, generates different secrets for each host, and store them to a given path.

**Comment by traviscosgrave** [comment]
see PR #36 regarding one approach to supporting kv2 (among a bunch of other things), still needs a modification to hashicorp/vault-ruby (see [PR 201](https://github.com/hashicorp/vault-ruby/pull/201))

**Comment by arcenik** [comment]
See also PR #41 which propose another approach to be v1 and v2 compatible.

**Comment by jhejl** [comment]
> See also PR #41 which propose another approach to be v1 and v2 compatible.

@arcenik can you please check the #41 PR, please? It feels like the `data` part should be constructed differently, resp. it should be put right behind the `mount` part and then the rest of the path. Current code doesn't work for me (even though it was merged into master already). Simple hack (sorry, not a rubyist) made it work for me:
```
--- /opt/puppetlabs/puppet/cache/lib/puppet/functions/hiera_vault.rb    2019-11-12 12:48:18.320664160 +0000
+++ /tmp/puppet-file20191112-396-1jzwdd7        2019-11-12 13:56:24.046216794 +0000
@@ -125,15 +125,15 @@
     kv_mounts.each_pair do |mount, paths|
       paths.each do |path|

-        secretpath = context.interpolate(File.join(mount, path))
-
-        context.explain { "[hiera-vault] Looking in path #{secretpath} for #{key}" }
-
         begin

+          secretpath = context.interpolate(File.join(mount, path))
+          context.explain { "[hiera-vault] Looking in path #{secretpath} for #{key}" }
           secret = get_kv_v1(secretpath, key)
           if secret.nil?
-            secret = get_kv_v2(secretpath, key)
+            secretpath_v2 = context.interpolate(File.join(mount, 'data', path))
+            context.explain { "[hiera-vault] Looking in path #{secretpath_v2} for #{key} via KV version 2" }
+            secret = get_kv_v2(secretpath_v2, key)
           end

         rescue Vault::HTTPConnectionError
@@ -189,7 +189,7 @@
   end

   def get_kv_v2(secretpath, key)
-    res = $vault.logical.read(File.join(secretpath,'data',key))
+    res = $vault.logical.read(File.join(secretpath,key))
     if ! res.nil?
       res=res.data[:data]
     end
```

**Comment by arcenik** [comment]
Hello @jhejl 

I think that you should make you own PR or create a new issue instead of putting file diff in an issue concerning an already merge PR.

Although, I don't see the point of moving the 'data' part of the path outside of get_kv_v2 function.
As it does not appear in the web UI of Vault, there no point to display it on the context.explain.

Best regards.

**Comment by maxadamo** [comment]
@arcenik can #41 be used? I mean, could you please create a tag if this is a working version?

**Comment by maxadamo** [comment]
wonder if #41  is usable and if we can create a tag.

**Comment by petems** [comment]
I just tested the change in #41 and it looks like it didnt work (I tried in my test environment at the time and it had but I think it was misconfifured)

I might be able to give this a go over the weekend and re-work it more 😄

**Comment by slauger** [comment]
I can confirm that the changes from #41 do not work with KV2.

I created to mounts - hiera_backend (as kv1) and hiera_backend (as kv2) with the same parameters inside.

```
---
version: 5

defaults:
  datadir: data
  data_hash: yaml_data

hierarchy:
  - name: 'Vault kv2 backend'
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
        - 'webserver::php_fpm_enable'
      address: 'https://dev01.example.tld:8200/'
      token: /etc/puppetlabs/puppet/vault-token
      default_field: value
      mounts:
        hiera_backend:
          - '%{trusted.certname}'
          - 'common'
  - name: 'Vault kv backend'
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
        - 'webserver::php_fpm_enable'
      address: 'https://dev01.example.tld:8200/'
      token: /etc/puppetlabs/puppet/vault-token
      default_field: value
      mounts:
        hiera_backend2:
          - '%{trusted.certname}'
          - 'common'
```

Current result:
```
-bash# puppet lookup webserver::php_fpm_enable --explain --compile --node=web02.example.tld
Searching for "webserver::php_fpm_enable"
  Global Data Provider (hiera configuration version 5)
    No such key: "webserver::php_fpm_enable"
  Environment Data Provider (hiera configuration version 5)
    Using configuration "/etc/puppetlabs/code/environments/production/hiera.yaml"
    Hierarchy entry "Vault kv2 backend"
      No such key: "webserver::php_fpm_enable"
      [hiera-vault] Client configured to connect to https://dev01.example.tld:8200/
      [hiera-vault] Looking in path hiera_backend2/web02.example.tld for webserver::php_fpm_enable
      [hiera-vault] Looking in path hiera_backend2/common for webserver::php_fpm_enable
    Hierarchy entry "Vault kv backend"
      Found key: "webserver::php_fpm_enable" value: false
```

Would be great if someone could provide a working solution for KV2.
