### ISSUE TITLE
Setting token: 'ENV["VAULT_TOKEN"]' doesn't work

### ISSUE THREAD

**Issue by tenajsystems** [petems/petems-hiera_vault#51]
@petems How is the ENV["VAULT_TOKEN"] supposed to be set? I have exported the token as `export VAULT_TOKEN=<token_here>` and in my hiera.yaml file, I have `token: 'ENV["VAULT_TOKEN"]'` but when I run puppet, it fails to lookup the key in vault. Setting the `token: '/path/to/token'` works however. 

Any thoughts on why setting `token: 'ENV["VAULT_TOKEN"]'` doesn't work? or I'm I doing something wrong?

**Comment by petems** [comment]
It has to be set within the context of the Puppet run as an environment variable, not hiera. 

So this could be done as `export VAULT_TOKEN=abc` in either

* `/etc/sysconfig/puppet` on RHEL and its derivatives
* `/etc/default/puppet` on Debian, Ubuntu, and their derivatives

Or in the Environment/EnvironmentFile setting in the Puppet systemd unit file.

**Comment by tenajsystems** [comment]
Thank you for the quick response. 

I am using Ubuntu and on puppet enterprise. I went into `/etc/default/pe-puppetserver` and added `export VAULT_TOKEN=<token here>` Do I need to set a value in token field like in the hiera sample below. As in where do I set `ENV["VAULT_TOKEN"]`. I am sure I am missing something but not sure what I am doing wrong
```
---

version: 5

hierarchy:
  - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
      ssl_verify: false
      address: https://vault.foobar.com:8200
      token: 'ENV["VAULT_TOKEN"]'
      default_field: value
      mounts:
        some_secret:
          - %{::trusted.certname}
          - common
        another_secret:
          - %{::trusted.certname}
          - common
```

**Comment by petems** [comment]
Remove the `token` field completely from the config, it will look for the environment value automatically:

```
---

version: 5

hierarchy:
  - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
      ssl_verify: false
      address: https://vault.foobar.com:8200
      default_field: value
      mounts:
        some_secret:
          - %{::trusted.certname}
          - common
        another_secret:
          - %{::trusted.certname}
          - common
```
