### ISSUE TITLE
If the Vault token becomes unavailable to the Hiera/Vault module, a secret is substituted with an empty string  

### ISSUE THREAD

**Issue by jhur7** [petems/petems-hiera_vault#54]
If the Vault token becomes unavailable, a secret is substituted with an empty string.  If you have thousands of systems, all configuration files would be updated with an empty string which could be a huge issue.  

Here is my Hiera configuration file.  I was able to recreate the issue by moving the token file to a .old extension. 
```
   - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
      address: https://hostname.example.com
      ssl_ca_cert: /etc/pki/tls/certs/example-root.pem
      token: /etc/puppetlabs/tokens/tokens_ro.txt
      default_field: value
      mounts:
        secrets/puppet_nogroup:
          - nodes/%{::trusted.certname}
          - common
```

In the nodes directory, I have a hostname1.net.yaml Hiera data file.  This has the following secret key lookup using the Hiera/Vault integration:

```virtual::secret_key: "%{lookup('password_virtual_key')}"```

This is the example of a Puppet run where the secret was substituted for an empty Puppet string:

```+++ /tmp/puppet-file20200724-17322-5p1vb9       2020-07-24 22:08:07.399183176 +0000
@@ -163,7 +163,7 @@
 # SECRET_KEY for all of them.
 #SECRET_KEY = secret_key.generate_or_read_from_file(
 #    os.path.join(LOCAL_PATH, '.secret_key_store'))
-SECRET_KEY = ‘REDACTED’
+SECRET_KEY = ''```

I am running Puppet 6.7 with petems-hiera_vault (v1.0.0).

Please advise on the best approach to resolve this.

**Comment by petems** [comment]
Hi, let me look into this for you. If it cant reach Vault, it should just error out and then hiera should return an error.

Q: Is there a reason you're using hiera over the new lookup avaliable with Puppet 6? This: https://forge.puppet.com/puppet/vault_lookup

**Comment by petems** [comment]
So from my testing, this isn't reproducible with the documented method of using lookup, either an automatic parameter lookup or explicit lookup in Puppet code:

```
---
version: 5
hierarchy:
  - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
      ssl_verify: false
      address: http://puppet:8200
      token: /etc/does_not_exist.txt
      default_field: value
      mounts:
        puppet:
          - '%{::trusted.certname}/'

```

```
# profile to deploy a puppet vault_message

class profile::vault_message {

  $vault_notify = lookup({"name" => "vault_notify"})
  notify { "testing vault ${vault_notify}":}

}
```

Error when running from Puppet:
```
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Function lookup() did not find a value for the name 'vault_notify' on node node1.vm
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

It's been a long time, but I do remember you being able to have functions within yaml files but it being heavily not recommended to do, because of issues like this. Is there a reason you're doing the lookup within the yaml file, rather than either doing an explicit lookup or using [automatic parameter lookup](https://puppet.com/docs/puppet/6.17/hiera_automatic.html#class_parameters)?
