### ISSUE TITLE
IGNORE-VAULT doesn't work correctly if set in the file.

### ISSUE THREAD

**Issue by italicninja** [petems/petems-hiera_vault#59]
Consider:

`vault.token`
```
[root@puppettest01 ~]# cat /etc/puppetlabs/puppetserver/vault.token
IGNORE-VAULT
```
And in `hiera.yaml`
```
  - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys: #Only lookup these
        - '^vault_.*'
        - '^.*password.*'
      ssl_verify: true
      address: <address>
      token: '/etc/puppetlabs/puppetserver/vault.token'
      default_field: value
      mounts:
        puppet:
          - 'nodes/%{facts.location}/%{trusted.certname}/'
```

I think this is because the check for Ignore is before the setting of the variable [hiera_vault.rb#L56](https://github.com/petems/petems-hiera_vault/blob/9697dd81cffdf16b2f6e1c7815bd62c7bef2860e/lib/puppet/functions/hiera_vault.rb#L56)

And the to read the file into the variable comes way after [hiera_vault.rb#L92](https://github.com/petems/petems-hiera_vault/blob/9697dd81cffdf16b2f6e1c7815bd62c7bef2860e/lib/puppet/functions/hiera_vault.rb#L92)
