### ISSUE TITLE
puppet lookup does not work as desired

### ISSUE THREAD

**Issue by saini01** [petems/petems-hiera_vault#60]
Dear Peter,

Thank you very much for your great work. I have a setup issue which I am unable to resolve. I must say I am fairly new to vault.

1. Our puppet infrastructure is at version 6.15 and vault server is installed on puppet master host with puppet module jsok-vault 2.3.0.
 ```
vault::version: '1.5.3'
vault::storage:
  file:
    path: /mnt/vault_store

vault::listener:
  - tcp:
      address: 0.0.0.0:8200
      tls_client_ca_file: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
      tls_cert_file: "/etc/puppetlabs/puppet/ssl/certs/HOSTNAME.pem"
      tls_key_file: "/etc/puppetlabs/puppet/ssl/private_keys/HOSTNAME.pem"

vault::enable_ui: true
vault::api_addr: "http://HOSTNAME:8200"
vault::extra_config:
  log_level: "Debug"
```
2. Vault server is a part of the puppet certificate infrastructure and it uses puppet agents certificate. Vault cert auth is enabled and puppet server CA certificate is added as trusted cert as described here https://github.com/voxpupuli/puppet-vault_lookup#setup

3. puppet-vault_lookup 0.1.1 and hiera_vault 1.0.0 is installed with debouncer and vault gem. Global hiera 5 file /etc/puppetlabs/puppet/hiera.yaml is extended to:
```
- name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - '^vault_.*'
        - '^.*_password$'
        - '^password.*'
      ssl_verify: true
      ssl_ca_cert: /etc/puppetlabs/puppet/ssl/certs/ca.pem
      address: VAULT_SERVER
      token: TOKEN
      default_field: value
      mounts:
        puppet_secret:
          - "%{::trusted.certname}"
          - "test"
```
4. Enabled kv2 engine with puppet_secret path and then added secrets with certname/hostname e.g. vault kv put puppet_secret/certname my_password=foo123

5. I am able to fetch it with curl on puppet master host: curl --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem -H "X-Vault-Token:$TOKEN" -X GET https://VAULT_SERVER:8200/v1/puppet_secret/data/certname
6. But `puppet lookup my_password --explain --compile` does not find the key. I tested it with root token and also generated prod, test policies with read, list permissions and generated token from that. All tokens work with curl but from puppet lookup command don't. 
```
Hierarchy entry "Hiera-vault lookup"
      No such key: "my_password"
      [hiera-vault] Client configured to connect to https://certname:8200
      [hiera-vault] Looking in path puppet_secret/certname for my_password
      [hiera-vault] Checking path: puppet_secret/certname/my_password
      [hiera-vault] Checking path: puppet_secret/certname/data/my_password
      [hiera-vault] Checking path: puppet_secret/data/certname/my_password
      [hiera-vault] Looking in path puppet_secret/test for my_password
      [hiera-vault] Checking path: puppet_secret/test/my_password
      [hiera-vault] Checking path: puppet_secret/test/data/my_password
      [hiera-vault] Checking path: puppet_secret/data/test/my_password
Function lookup() did not find a value for the name 'my_password'
```
7. I also enabled audit logging and I can see all the requests that were made to vault server but I don't see any errors.
8. Using deferred function in a manifest is also getting me no results. 
```
$vault_notify = Deferred('vault_lookup::lookup', ['puppet_secret/data/certname/my_password', 'https://VAULT_SERVER:8200'])
  notify {"testing vault ${vault_notify}":}
```
Do you have any hint what might be going wrong? I am stuck with this problem for so many days :(. Any help will be much appreciated. Many thanks!
