### ISSUE TITLE
question: using wildcards in mounts paths

### ISSUE THREAD

**Issue by dthpulse** [petems/petems-hiera_vault#87]
Hi, I'm looking for the way to use wildcards in mounts paths. 
I would need something like this to make work, but it doesn't with hiera_vault in my hiera5 config:
```
---
version: 5

hierarchy:
  - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - "^vault_.*"
        - "^.*_password$"
        - "^password.*"
      ssl_verify: false
      address: https://vault.foobar.com:8200
      token: <insert-your-vault-token-here>
      default_field: value
      mounts:
        some_secret:
          - %{::trusted.certname}/*
          - common/*
        another_secret:
          - %{::trusted.certname}/*
          - common/*
```
Any hint, please?
Thanks
